// get random joke from other API
GET http://localhost:3000/jokes/from-api
Content-Type: 


###

// create a new joke to the db
POST http://localhost:3000/jokes
Content-Type: application/json

{
    "joke": "This is another chuck norris joke, ok."
}


###
// get all jokes data from db
GET http://localhost:3000/jokes


###

// delete joke by its id
DELETE  http://localhost:3000/jokes/5fc9e4c33314952ea5028af7


###

// get many random jokes data from db
GET http://localhost:3000/jokes/many/5


###

// delete all stored jokes from db storage
DELETE  http://localhost:3000/jokes/all

###
// get 5 jokes data with body param from db
POST http://localhost:3000/jokes/all
Content-Type: application/json

{
    "limit": 5, // the amount of jokes requested
    "page": 1
}

###

// get jokes data with query param of limit and page from db
GET http://localhost:3000/jokes/paginate?limit=100&page=14