// get random joke from other API
GET http://localhost:3000/jokes/from-api
Content-Type: 


###

// fetch and create new jokes to the db
POST http://localhost:3000/jokes
Content-Type: application/json

{
    "amount": 10
}


###
// get all jokes data from db
GET http://localhost:3000/jokes


###

// delete joke by its id
DELETE  http://localhost:3000/jokes/5fc9e4c33314952ea5028af7


###

// get 5 random jokes data from db
GET http://localhost:3000/jokes/many/5


###

// delete all stored jokes from db storage
GET  http://localhost:3000/jokes/delete-all


###

// get jokes data with query param of limit and page from db
GET http://localhost:3000/jokes/paginate?limit=2&page=1


###

// get analysis of random jokes data from db
GET http://localhost:3000/jokes/analysis/190